import { Step } from './step.model';

export const steps: Step[] = [
  {
    id: 1,
    year: 1995,
    title: 'Il était une fois...',
    coordinates: { lat: 49.25631, lng: 4.03994 },
    hint: "Ton pèlerinage commence là où ton fil vital s'est noué un mois avant l'heure, dans ce havre de nouveaux départs baptisé du nom d'un apôtre.",
    lockedImage:
      'https://www.amisdejesus.net/wp-content/uploads/2017/02/saint-andre.jpg',
    unlockedContent: 'Te voilà revenue à ton point de départ',
    cassette: 'clinique.ogg',
    isUnlocked: false,
    isAccessible: true,
    isCurrent: true,
    canPostpone: false,
  },
  {
    id: 2,
    year: 1996,
    title: 'Constance est mère de sureté',
    coordinates: { lat: 49.24612, lng: 4.04435 },
    hint: 'Ta prochaine étape se trouve là où tu as vécu tes premières expériences sociales, entre les bras rassurants de Constance et Domi.',
    unlockedContent:
      "Entre cris et câlins, c'est ici que tu as commencé à te forger",
    cassette: 'creche.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 3,
    year: 1998,
    title: 'La mâchoire en vrac',
    coordinates: { lat: 49.23477947071199, lng: 4.043672392989468 },
    hint: 'Trouve le théâtre de tes premières boums et de tes matins Christophe Maé.',
    unlockedContent: 'Tu te rappelles les pique-niques dans le salon ?',
    cassette: '1erappart.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 4,
    year: 1999,
    title: 'Premier envol',
    coordinates: { lat: 49.242422746489446, lng: 4.04163516909009 },
    hint: 'Non loin de chez "N", ce parking a été le théâtre de ton départ vers ton premier voyage scolaire.',
    unlockedContent:
      "C'est ici que tu as fait preuve d'une surprenante autonomie",
    cassette: '1ervoyage.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 5,
    year: 2000,
    title: 'Décision capillaire',
    coordinates: { lat: 49.24333133844844, lng: 4.043547274465178 },
    hint: 'Ta prochaine étape se trouve là où les ciseaux ont rencontré ta chevelure pour la première fois, sur ta propre initiative',
    unlockedContent: 'Et si on allait se faire une petite coupe ?',
    cassette: 'coiffeur.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 6,
    year: 2004,
    title: 'Qui a eu cette idée folle ?',
    coordinates: { lat: 49.245726105630325, lng: 4.042023106499553 },
    hint: "Cherche ce lieu où tu as rencontré ta première âme soeur d'amitié",
    unlockedContent: 'Te voici revenue sur les bancs de ton enfance',
    cassette: 'nicolasroland.ogg\n',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 7,
    year: 2004,
    title: 'A travers le grillage',
    coordinates: { lat: 49.23821876348824, lng: 3.98220775778159 },
    hint: "La suite de ton pèlerinage te mène vers l'endroit où, après avoir tant insisté auprès de tes parents, tu as trouvé ton premier grand amour",
    unlockedContent: 'Dix-huit ans de bonheur ont commencé entre ces murs',
    cassette: 'mirabelle.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 8,
    year: 2006,
    title: "La révélation par l'échec",
    coordinates: { lat: 49.25081820643331, lng: 4.024202339648994 },
    hint: 'Cherche ce lieu où, à onze ans, tu as enfilé des gants trop grands pour découvrir une activité que tu as absolument détestée',
    unlockedContent: 'Prête à remettre les gants ?',
    cassette: 'boxe.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 9,
    year: 2007,
    title: 'Footings complices',
    coordinates: { lat: 49.240084123483726, lng: 4.056045731811416 },
    hint: 'Trouve ce lieu de verdure où tu traînais parfois la patte, mais où tu chérissais chaque moment passé avec ton père',
    unlockedContent: 'Et si on faisait un tour de course ensemble ?',
    cassette: 'parcchampagne.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 10,
    year: 2007,
    title: 'Bébé gâteaux',
    coordinates: { lat: 49.2524914220847, lng: 4.038133130546834 },
    hint: "Dirige-toi vers cette institution où, assise sur les marches de l'immeuble d'en face, tu passais du temps avec ton premier vrai copain",
    unlockedContent:
      "Le lieu où ton trio d'amitié s'est formé t'accueille de nouveau",
    cassette: 'notredame.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 11,
    year: 2025,
    title: 'Fumées et Friandises',
    coordinates: { lat: 49.25661324202751, lng: 4.034847102912872 },
    hint: 'todo',
    cassette: 'todo',
    unlockedContent: 'todo',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: true,
  },
  {
    id: 12,
    year: 2010,
    title: 'Mélodie au piano',
    coordinates: { lat: 49.27021205181508, lng: 4.048527289656747 },
    hint: "La suite de ton pèlerinage te mène vers le lieu où tu as découvert les joies et les peines d'une relation amoureuse adolescente",
    unlockedContent:
      'Te voici revenue sur les terres de ton premier grand amour',
    cassette: 'olivier.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 13,
    year: 2011,
    title: 'Tournant familial',
    coordinates: { lat: 49.259139943901914, lng: 4.034989509268428 },
    hint: "Un lieu aimé qui a pourtant été témoin d'un bouleversement familial important",
    unlockedContent: "Un chapitre de transformations s'ouvre ici",
    cassette: '2emeappart.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 14,
    year: 2013,
    title: 'Teenage Dream',
    coordinates: { lat: 49.25925662707037, lng: 4.035991119769239 },
    hint: "Tes années les plus vibrantes avant d'obtenir le précieux sésame",
    unlockedContent: 'Entre ces murs, tu te préparais à conquérir le monde',
    cassette: 'jean23.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 15,
    year: 2014,
    title: 'La vieille dame de pierre',
    coordinates: { lat: 49.25337226194044, lng: 4.032698499271173 },
    hint: 'Tu lui as prêté une âme et des souvenirs dans un texte primé',
    unlockedContent: "Grâce à ses pierres séculaires, ton talent s'est révélé",
    cassette: 'cathedrale.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 16,
    year: 2016,
    title: 'Fléchettes et nounours',
    coordinates: { lat: 49.25659497101606, lng: 4.0375723673488215 },
    hint: 'De longues heures à bavarder en inhalant de la fumée',
    unlockedContent: "C'est ici que ton cœur a reconnu son âme sœur",
    cassette: 'rueceres.ogg\n',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 17,
    year: 2016,
    title: 'Grandir loin des repères',
    coordinates: { lat: 49.26439146128293, lng: 4.034260702420404 },
    hint: "On y fait le même produit que dans la cité des ducs, mais la cité des ducs c'est trop loin",
    unlockedContent: "J'espère au moins qu'elle sera bonne...",
    cassette: 'dijon.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 18,
    year: 2017,
    title: 'Pâte à sel et forêt',
    coordinates: { lat: 49.16050963798406, lng: 4.116062968151446 },
    hint: 'Tu y as laissé de beaux souvenirs, même sans le diplôme officiel !',
    unlockedContent: 'As-tu déjà gardé un petit Johnatan ?',
    cassette: 'centreaere.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 19,
    year: 2017,
    title: 'Le grenier des secrets',
    coordinates: { lat: 49.15597270898161, lng: 4.110769234173817 },
    hint: "Yoda et Micha t'y ont accueilli bien des années",
    unlockedContent: 'Une partie de Uno dans le jardin ?',
    cassette: 'domi.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 20,
    year: 2018,
    title: 'Nouvelles du Lundi',
    coordinates: { lat: 49.25671789242281, lng: 4.025982551424577 },
    hint: 'Entre deux bouchées, une dose hebdomadaire de soleil',
    unlockedContent: "Ta plume au service de l'optimisme !",
    cassette: 'mps.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 21,
    year: 2018,
    title: 'Pomme au volant',
    coordinates: { lat: 49.25774281528567, lng: 4.040371701454344 },
    hint: 'todo',
    unlockedContent: 'todo',
    cassette: 'permis.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 22,
    year: 2019,
    title: 'Cocon humide',
    coordinates: { lat: 49.247430734950356, lng: 4.041221515154622 },
    hint: 'todo',
    unlockedContent: 'todo',
    cassette: '112.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 23,
    year: 2020,
    title: 'Envolée bleue',
    coordinates: { lat: 49.25679159143847, lng: 4.020700691974677 },
    hint: 'todo',
    unlockedContent: 'todo',
    cassette: 'setup.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 24,
    year: 2021,
    title: 'Rien ne sert de courir...',
    coordinates: { lat: 49.261183896482265, lng: 4.033501333332016 },
    hint: 'todo',
    unlockedContent: 'todo',
    cassette: 'rir.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 25,
    year: 2024,
    title: 'All I want for my life is you',
    coordinates: { lat: 49.28882003648126, lng: 3.8055820883375007 },
    hint: 'todo',
    unlockedContent: 'todo',
    cassette: 'mariage.ogg',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
  {
    id: 26,
    year: 2025,
    title: 'Barbotage fines bulles',
    coordinates: { lat: 49.2542752084596, lng: 4.038388808701627 },
    hint: 'todo',
    unlockedContent: 'todo',
    cassette: 'todo',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: true,
  },
  {
    id: 27,
    year: 2025,
    title: 'Retour au cocon',
    coordinates: { lat: 49.259961235874975, lng: 4.039008576706121 },
    hint: 'todo',
    unlockedContent: 'todo',
    cassette: 'todo',
    isUnlocked: false,
    isAccessible: false,
    isCurrent: false,
    canPostpone: false,
  },
];
// export const steps: Step[] = [
//   {
//     id: 1,
//     year: 1995,
//     title: 'Il était une fois...',
//     coordinates: { lat: 49.25631, lng: 4.03994 },
//     hint: "Notre pèlerinage commence là où notre fil vital s'est noué un mois avant l'heure, dans ce havre de nouveaux départs baptisé du nom d'un apôtre",
//     lockedImage:
//       'https://www.amisdejesus.net/wp-content/uploads/2017/02/saint-andre.jpg',
//     unlockedContent: 'Félicitations pour avoir trouvé le premier lieu !',
//     cassette: '1.ogg',
//     isUnlocked: false,
//     isAccessible: true,
//     isCurrent: true,
//     canPostpone: false,
//   },
//   {
//     id: 2,
//     title: 'Constance est mère de sureté',
//     coordinates: { lat: 49.259205055989895, lng: 4.0359924197744945 },
//     hint: 'Entre les vieux chênes, un passage se révèle',
//     lockedImage:
//       'https://images.unsplash.com/photo-1511497584788-876760111969?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
//     unlockedContent:
//       "Vous avez découvert le passage caché ! Il est temps de s'aventurer plus profondément.",
//     unlockedImage:
//       'https://images.unsplash.com/photo-1507501336603-6e31db2be093?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
//     isUnlocked: false,
//     isAccessible: false,
//     isCurrent: false,
//     year: 1999,
//     cassette: 'sample.mp3',
//     canPostpone: true,
//   },
//   {
//     id: 3,
//     title: 'Le pot pourri',
//     coordinates: { lat: 49.2599726573367, lng: 4.031611159574977 },
//     hint: "Là où l'eau rencontre la pierre, l'artefact attend",
//     lockedImage:
//       'https://images.unsplash.com/photo-1519677584237-752f8853252e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
//     lockedVideo:
//       'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
//     unlockedContent:
//       "L'ancien artefact est à vous ! Vous avez terminé la chasse au trésor.",
//     unlockedImage:
//       'https://images.unsplash.com/photo-1531873568041-086189c151da?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80',
//     unlockedVideo:
//       'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4',
//     isUnlocked: false,
//     isAccessible: false,
//     isCurrent: false,
//     year: 2007,
//     cassette: 'sample.mp3',
//     canPostpone: false,
//   },

//   {
//     id: 4,
//     year: 2001,
//     title: 'Une étape supplémentaire',
//     coordinates: { lat: 49.25, lng: 4.03 },
//     hint: "Un indice pour l'étape 4.",
//     unlockedContent: "Contenu débloqué de l'étape 4.",
//     cassette: 'sample.mp3',
//     isUnlocked: false,
//     isAccessible: false,
//     isCurrent: false,
//     canPostpone: false,
//   },
// ];
